import { DefaultTheme } from "react-native-paper";

export const darkTheme = {
  ...DefaultTheme,

  colors: {
    appContainer: "#1a1f3a",
    primary: "#2d3561",
    secondary: "#6c7ce7",
    tertiary: "#ff6b9d",
    white: "#ffffff",
    headerText: "#ffffff",
    fadeText: "#8b9dc3",
    listItemText: "#e4e8f5",
    cardBackground: "#2d3561",
    shadowColor: "#000000",
    gradientStart: "#1a1f3a",
    gradientEnd: "#2d3561",
    accent: "#6c7ce7",
    success: "#4ade80",
    danger: "#f87171",

    notification: null,
    onSurface: null,
    surface: null,
    error: null,
    text: "#e4e8f5",
    placeholder: "#8b9dc3",
    background: "#1a1f3a",
  },
  sizes: {
    headerText: 32,
    addTodoIconSize: 56,
    todosStatus: 18,
    todosText: 16,
    listItemIcons: 24,
    listItemDate: 12,
    headerIcon: 24,
    lastTodoStatusText: 11,
    borderRadius: 16,
    cardPadding: 20,
  },
  fontWeights: {
    regular: "400",
    medium: "500",
    bold: "700",
    italic: "italic",
  },
  shadows: {
    small: {
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 2,
    },
    medium: {
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.15,
      shadowRadius: 8,
      elevation: 4,
    },
    large: {
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.2,
      shadowRadius: 16,
      elevation: 8,
    },
  },
};

export const lightTheme = {
  ...DefaultTheme,

  colors: {
    appContainer: "#f8fafc",
    primary: "#ffffff",
    secondary: "#6366f1",
    tertiary: "#8b5cf6",
    white: "#ffffff",
    headerText: "#1e293b",
    listItemText: "#334155",
    cardBackground: "#ffffff",
    shadowColor: "#000000",
    gradientStart: "#f8fafc",
    gradientEnd: "#e2e8f0",
    accent: "#6366f1",
    success: "#10b981",
    danger: "#ef4444",
    fadeText: "#64748b",

    notification: null,
    onSurface: null,
    surface: null,
    error: null,
    text: "#334155",
    placeholder: "#94a3b8",
    background: "#f8fafc",
  },
  sizes: {
    headerText: 32,
    addTodoIconSize: 56,
    todosStatus: 18,
    todosText: 16,
    listItemIcons: 24,
    listItemDate: 12,
    headerIcon: 24,
    lastTodoStatusText: 11,
    borderRadius: 16,
    cardPadding: 20,
  },
  fontWeights: {
    regular: "400",
    medium: "500",
    bold: "700",
    italic: "italic",
  },
  shadows: {
    small: {
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.05,
      shadowRadius: 4,
      elevation: 2,
    },
    medium: {
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.1,
      shadowRadius: 8,
      elevation: 4,
    },
    large: {
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.15,
      shadowRadius: 16,
      elevation: 8,
    },
  },
};
